// Copyright 2013-2026:
//   GobySoft, LLC (2013-)
//   Massachusetts Institute of Technology (2007-2014)
//   Community contributors (see AUTHORS file)
// File authors:
//   Cadmus To <cadmus.to+dev@gmail.com>
//
//
// This file is part of the Dynamic Compact Control Language Library
// ("DCCL").
//
// DCCL is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or
// (at your option) any later version.
//
// DCCL is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with DCCL.  If not, see <http://www.gnu.org/licenses/>.
syntax = "proto2";
import "dccl/option_extensions.proto";
package dccl.test;

message FloatMsg
{
    option (dccl.msg).id = 1501;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 4;

    optional float f = 1 [
        (dccl.field).max = 10,
        (dccl.field).min = -10,
        (dccl.field).precision = 7
    ];
}

message NegativePrecisionFloatMsg
{
    option (dccl.msg).id = 2101;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 4;

    optional float f = 1 [
        (dccl.field).max = 20,
        (dccl.field).min = -20,
        (dccl.field).precision = -1
    ];
}

message PrecisionRangeFloatMsg
{
    option (dccl.msg).id = 2201;
    option (dccl.msg).max_bytes = 256;
    option (dccl.msg).codec_version = 4;

    optional float prec0 = 1 [
        (dccl.field).max = 10000000,
        (dccl.field).min = -10000000,
        (dccl.field).precision = 0
    ];
    optional float prec1 = 2 [
        (dccl.field).max = 1000000,
        (dccl.field).min = -1000000,
        (dccl.field).precision = 1
    ];
    optional float prec2 = 3 [
        (dccl.field).max = 100000,
        (dccl.field).min = -100000,
        (dccl.field).precision = 2
    ];
    optional float prec3 = 4 [
        (dccl.field).max = 10000,
        (dccl.field).min = -10000,
        (dccl.field).precision = 3
    ];
    optional float prec4 = 5 [
        (dccl.field).max = 1000,
        (dccl.field).min = -1000,
        (dccl.field).precision = 4
    ];
    optional float prec5 = 6 [
        (dccl.field).max = 100,
        (dccl.field).min = -100,
        (dccl.field).precision = 5
    ];
    optional float prec6 = 7 [
        (dccl.field).max = 10,
        (dccl.field).min = -10,
        (dccl.field).precision = 6
    ];
}
