// Copyright 2024:
//   GobySoft, LLC (2013-)
//   Community contributors (see AUTHORS file)
// File authors:
//   Toby Schneider <toby@gobysoft.org>
//
//
// This file is part of the Dynamic Compact Control Language Library
// ("DCCL").
//
// DCCL is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or
// (at your option) any later version.
//
// DCCL is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with DCCL.  If not, see <http://www.gnu.org/licenses/>.
// tests CRC field codecs (dccl.crc16 and dccl.crc32)

syntax = "proto2";

import "dccl/option_extensions.proto";

package dccl.test;

// Test message with CRC-16 checksum
message TestCRC16
{
    option (dccl.msg).id = 10;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 5;

    required int32 x = 1 [(dccl.field) = { min: -10000, max: 10000 }];
    required int32 y = 2 [(dccl.field) = { min: -10000, max: 10000 }];
    required uint32 crc = 100 [
        (dccl.field) = { codec: "dccl.crc16" }
    ];
}

// Test message with CRC-32 checksum
message TestCRC32
{
    option (dccl.msg).id = 11;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 5;

    required int32 x = 1 [(dccl.field) = { min: -10000, max: 10000 }];
    required int32 y = 2 [(dccl.field) = { min: -10000, max: 10000 }];
    required uint32 crc = 100 [
        (dccl.field) = { codec: "dccl.crc32" }
    ];
}
