// Copyright 2024:
//   GobySoft, LLC (2013-)
//   Community contributors (see AUTHORS file)
// File authors:
//   Toby Schneider <toby@gobysoft.org>
//
//
// This file is part of the Dynamic Compact Control Language Library
// ("DCCL").
//
// DCCL is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or
// (at your option) any later version.
//
// DCCL is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with DCCL.  If not, see <http://www.gnu.org/licenses/>.
// tests CRC field codecs (dccl.crc16 and dccl.crc32)

syntax = "proto2";

import "dccl/option_extensions.proto";

package dccl.test;

// Test message with CRC-16 checksum
message TestCRC16
{
    option (dccl.msg).id = 10;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 5;

    required int32 x = 1 [(dccl.field) = { min: -10000, max: 10000 }];
    required int32 y = 2 [(dccl.field) = { min: -10000, max: 10000 }];
    required uint32 crc = 100 [
        (dccl.field) = { codec: "dccl.crc16" }
    ];
}

// Test message with CRC-32 checksum
message TestCRC32
{
    option (dccl.msg).id = 11;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 5;

    required int32 x = 1 [(dccl.field) = { min: -10000, max: 10000 }];
    required int32 y = 2 [(dccl.field) = { min: -10000, max: 10000 }];
    required uint32 crc = 100 [
        (dccl.field) = { codec: "dccl.crc32" }
    ];
}

message CRCEmbeddedMsg
{
    required int32 a = 1 [(dccl.field) = { min: -100, max: 100 }];
    optional string b = 2 [(dccl.field).max_length = 8];
}

// Exercises field types whose codecs modify the Bitset they decode from (optional and
// variable length fields), plus repeated and embedded fields, all of which must be covered
// by the CRC just as they are on encoding
message TestCRCAllFields
{
    option (dccl.msg).id = 12;
    option (dccl.msg).max_bytes = 128;
    option (dccl.msg).codec_version = 5;

    required int32 x = 1 [(dccl.field) = { min: -10000, max: 10000 }];
    optional int32 y = 2 [(dccl.field) = { min: -10000, max: 10000 }];
    optional string s = 3 [(dccl.field).max_length = 10];
    repeated int32 r = 4 [(dccl.field) = { min: 0, max: 100, max_repeat: 4 }];
    required CRCEmbeddedMsg em = 5;
    optional CRCEmbeddedMsg em_opt = 6;
    optional int32 h = 7 [(dccl.field) = { min: 0, max: 100, in_head: true }];

    required uint32 crc = 100 [(dccl.field) = { codec: "dccl.crc32" }];
}

// The bits identifying which field of a oneof is set are part of the body, and so must be
// covered by the CRC as well
message TestCRCOneof
{
    option (dccl.msg).id = 13;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 5;

    oneof choice
    {
        int32 x = 1 [(dccl.field) = { min: -10000, max: 10000 }];
        int32 y = 2 [(dccl.field) = { min: -10000, max: 10000 }];
    }

    required uint32 crc = 100 [(dccl.field) = { codec: "dccl.crc32" }];
}

message CRCBadEmbeddedMsg
{
    required int32 a = 1 [(dccl.field) = { min: -100, max: 100 }];
    required uint32 crc = 100 [(dccl.field) = { codec: "dccl.crc32" }];
}

message TestCRCBadNested
{
    option (dccl.msg).id = 14;
    option (dccl.msg).max_bytes = 32;
    option (dccl.msg).codec_version = 5;

    required CRCBadEmbeddedMsg em = 1;
}
