from typing import Iterable, Mapping

from google.protobuf.descriptor import Descriptor
from google.protobuf.message import Message

BytesLike = bytes | bytearray | memoryview
TypeRef = str | Message | Descriptor


class DcclException(Exception):
    pass


class OutOfRangeException(DcclException):
    pass


def loadProtoFile(path: str) -> None: ...
def addProtoIncludePath(path: str) -> None: ...

def set_time_clock_epoch_seconds(seconds: int) -> None: ...
def set_time_clock_epoch_microseconds(usec: int) -> None: ...
def use_system_clock() -> None: ...


class Codec:
    def __init__(self, id_codec: str = ..., library_path: str = ...) -> None: ...

    def id(self, value: BytesLike | TypeRef) -> int: ...
    def size(self, message: Message) -> int: ...
    def encode(self, message: Message, header_only: bool = ...) -> bytes: ...
    def decode(self, data: BytesLike, header_only: bool = ...) -> Message: ...
    def decode_into(self, data: BytesLike, message: Message, header_only: bool = ...) -> Message: ...

    def load(self, type_or_message: TypeRef) -> None: ...
    def load_hash(self, type_or_message: TypeRef) -> int: ...
    def unload(self, type_or_message: TypeRef | int) -> None: ...
    def unload_all(self) -> None: ...
    def load_library(self, path: str) -> None: ...

    def set_crypto_passphrase(self, phrase: str, ids_to_skip: Iterable[int] | None = ...) -> None: ...
    def set_strict(self, enabled: bool) -> None: ...
    def set_console_width(self, width: int) -> None: ...
    def set_id_codec(self, name: str) -> None: ...
    def get_id_codec(self) -> str: ...

    def info(self, type_or_message: TypeRef, user_id: int = ...) -> str: ...
    def info_all(self) -> str: ...
    def min_size(self, type_or_message: TypeRef) -> int: ...
    def max_size(self, type_or_message: TypeRef) -> int: ...
    def loaded(self) -> Mapping[int, str]: ...
